name: Course Management System
values:
  - key: baseUrl
    value: 'http://localhost:8000'
    enabled: true
    type: default
  - key: userId
    value: ''
    enabled: true
    type: default
  - key: courseId
    value: ''
    enabled: true
    type: default
  - key: instructorId
    value: ''
    enabled: true
    type: default
  - key: studentId
    value: ''
    enabled: true
    type: default
  - key: fileId
    value: ''
    enabled: true
    type: default
  - key: storedName
    value: ''
    enabled: true
    type: default
  - key: enrollmentId
    value: ''
    enabled: true
    type: default
